/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate=new Date(2006,3-1,13,6,0,4,360);
var stats=[{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:166,traffic:1001,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:139,traffic:1004,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:133,traffic:814,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:93,traffic:550,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:93,traffic:133,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:59,traffic:386,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/index.htm',hits:53,traffic:47,name:'index',ext:'htm',relurl:'dds.arc/new-site/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:52,traffic:43,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/lampServer/index.htm',hits:51,traffic:74,name:'index',ext:'htm',relurl:'inTec/lampServer/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:47,traffic:346,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:39,traffic:141,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:33,traffic:156,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/maxlength.htm',hits:32,traffic:90,name:'maxlength',ext:'htm',relurl:'dzLib/maxlength.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:32,traffic:325,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:31,traffic:37,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc/dzLib/index.htm',hits:30,traffic:41,name:'index',ext:'htm',relurl:'arc/dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:27,traffic:48,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:26,traffic:134,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:23,traffic:16,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:23,traffic:361,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:23,traffic:31,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:22,traffic:26,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:20,traffic:17,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:18,traffic:10,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog-2004.htm',hits:17,traffic:239,name:'jsLog-2004',ext:'htm',relurl:'logs/jsLog-2004.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:16,traffic:21,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:16,traffic:140,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:16,traffic:14,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:16,traffic:22,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:16,traffic:60,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:15,traffic:51,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:15,traffic:7,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:15,traffic:6,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/index.htm',hits:15,traffic:22,name:'index',ext:'htm',relurl:'google/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:14,traffic:78,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:14,traffic:33,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:13,traffic:46,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_jsListSearchSpeedTest.htm',hits:13,traffic:1,name:'_jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/_jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:13,traffic:31,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:12,traffic:6,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:12,traffic:30,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:12,traffic:4,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/doekman/index.htm',hits:12,traffic:40,name:'index',ext:'htm',relurl:'dds.arc/doekman/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:11,traffic:18,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:11,traffic:8,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toLiteral.htm',hits:11,traffic:22,name:'toLiteral',ext:'htm',relurl:'dzLib/toLiteral.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:11,traffic:45,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_south.htm',hits:11,traffic:2,name:'all_south',ext:'htm',relurl:'dds.arc/miniwebventure/all_south.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:11,traffic:5,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/chknav.htm',hits:10,traffic:44,name:'chknav',ext:'htm',relurl:'dzLib/chknav.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:10,traffic:22,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:10,traffic:27,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:10,traffic:30,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:9,traffic:24,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:9,traffic:1,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:9,traffic:7,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:9,traffic:11,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:8,traffic:3,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:8,traffic:8,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:8,traffic:51,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/vierhoek.html',hits:8,traffic:9,name:'vierhoek',ext:'htm',relurl:'dds.arc/vierhoek.html'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:8,traffic:2,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/testToLiteral.htm',hits:8,traffic:37,name:'testToLiteral',ext:'htm',relurl:'dzLib/testToLiteral.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:8,traffic:5,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_template.htm',hits:8,traffic:2,name:'_template',ext:'htm',relurl:'jsPrj/_template.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:8,traffic:29,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:8,traffic:5,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/html-edit.htm',hits:8,traffic:1,name:'html-edit',ext:'htm',relurl:'jsPrj/html-edit.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:8,traffic:5,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/tools/index.htm',hits:8,traffic:6,name:'index',ext:'htm',relurl:'tools/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:7,traffic:17,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image14.html',hits:7,traffic:2,name:'Image14',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image14.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:7,traffic:1,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nt.html',hits:7,traffic:7,name:'nt',ext:'htm',relurl:'dds.arc/Australia/nt.html'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:7,traffic:5,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image12.html',hits:7,traffic:1,name:'Image12',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image12.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/kitchen.htm',hits:7,traffic:1,name:'kitchen',ext:'htm',relurl:'dds.arc/miniwebventure/kitchen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/entrance.htm',hits:7,traffic:3,name:'entrance',ext:'htm',relurl:'dds.arc/miniwebventure/entrance.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image6.html',hits:6,traffic:1,name:'Image6',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image6.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image13.html',hits:6,traffic:2,name:'Image13',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image13.html'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:6,traffic:23,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image21.html',hits:6,traffic:1,name:'Image21',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image21.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image18.html',hits:6,traffic:1,name:'Image18',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image18.html'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:6,traffic:4,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image22.html',hits:6,traffic:2,name:'Image22',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image22.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/olrik.html',hits:6,traffic:11,name:'olrik',ext:'htm',relurl:'dds.arc/olrik.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery2.html',hits:6,traffic:6,name:'photoGallery2',ext:'htm',relurl:'dds.arc/Australia/photoGallery2.html'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:6,traffic:11,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/hallwest.htm',hits:6,traffic:1,name:'hallwest',ext:'htm',relurl:'dds.arc/miniwebventure/hallwest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image2.html',hits:6,traffic:1,name:'Image2',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image2.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005.html',hits:6,traffic:17,name:'Safier2005',ext:'htm',relurl:'Safier2005/Safier2005.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image11.html',hits:6,traffic:2,name:'Image11',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image11.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/jsTools.htm',hits:6,traffic:19,name:'jsTools',ext:'htm',relurl:'dds.arc/jsTools.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:6,traffic:4,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image19.html',hits:6,traffic:1,name:'Image19',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image19.html'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:6,traffic:7,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/tabe/index.htm',hits:6,traffic:2,name:'index',ext:'htm',relurl:'dds.arc/tabe/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:5,traffic:8,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/go_down.htm',hits:5,traffic:1,name:'go_down',ext:'htm',relurl:'dds.arc/miniwebventure/go_down.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/en.htm',hits:5,traffic:6,name:'en',ext:'htm',relurl:'google/en.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image15.html',hits:5,traffic:2,name:'Image15',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image15.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image23.html',hits:5,traffic:2,name:'Image23',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image23.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/halleast.htm',hits:5,traffic:1,name:'halleast',ext:'htm',relurl:'dds.arc/miniwebventure/halleast.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image28.html',hits:5,traffic:2,name:'Image28',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image28.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/default.htm',hits:5,traffic:3,name:'default',ext:'htm',relurl:'dds.arc/new-site/default.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/note.htm',hits:5,traffic:0,name:'note',ext:'htm',relurl:'dds.arc/miniwebventure/icons/note.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/var-inspect.html',hits:5,traffic:5,name:'var-inspect',ext:'htm',relurl:'dzLib/var-inspect.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_north.htm',hits:5,traffic:0,name:'all_north',ext:'htm',relurl:'dds.arc/miniwebventure/all_north.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/doeke.htm',hits:5,traffic:5,name:'doeke',ext:'htm',relurl:'dds.arc/miniwebventure/doeke.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image3.html',hits:5,traffic:1,name:'Image3',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image3.html'}
,{url:'http://www.xs4all.nl/~zanstra/google/nl.htm',hits:5,traffic:9,name:'nl',ext:'htm',relurl:'google/nl.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image29.html',hits:4,traffic:1,name:'Image29',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image29.html'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:4,traffic:2,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nz1.html',hits:4,traffic:4,name:'nz1',ext:'htm',relurl:'dds.arc/Australia/nz1.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image4.html',hits:4,traffic:2,name:'Image4',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image4.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image32.html',hits:4,traffic:1,name:'Image32',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image32.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image31.html',hits:4,traffic:1,name:'Image31',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image31.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/key_lock.htm',hits:4,traffic:1,name:'key_lock',ext:'htm',relurl:'dds.arc/miniwebventure/icons/key_lock.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/koop.htm',hits:4,traffic:1,name:'koop',ext:'htm',relurl:'dds.arc/miniwebventure/koop.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:4,traffic:4,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:4,traffic:21,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image30.html',hits:4,traffic:1,name:'Image30',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image30.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image24.html',hits:4,traffic:2,name:'Image24',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image24.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image26.html',hits:4,traffic:2,name:'Image26',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image26.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/contact.html',hits:4,traffic:7,name:'contact',ext:'htm',relurl:'dds.arc/contact.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image25.html',hits:4,traffic:1,name:'Image25',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image25.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image5.html',hits:4,traffic:1,name:'Image5',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image5.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image10.html',hits:3,traffic:1,name:'Image10',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image10.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image27.html',hits:3,traffic:1,name:'Image27',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image27.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image20.html',hits:3,traffic:1,name:'Image20',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image20.html'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:3,traffic:3,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:3,traffic:0,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/cch.html',hits:3,traffic:6,name:'cch',ext:'htm',relurl:'dds.arc/Australia/cch.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/money.htm',hits:3,traffic:0,name:'money',ext:'htm',relurl:'dds.arc/miniwebventure/icons/money.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/looknote.htm',hits:3,traffic:0,name:'looknote',ext:'htm',relurl:'dds.arc/miniwebventure/looknote.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/capeyork.html',hits:3,traffic:4,name:'capeyork',ext:'htm',relurl:'dds.arc/Australia/capeyork.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image17.html',hits:3,traffic:2,name:'Image17',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image17.html'}
];
