/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2005_6=new Date(2005,9-1,6,22,9,27,283);
var stats_2005_6=[{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:372,traffic:2840,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:327,traffic:2081,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:273,traffic:4650,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:263,traffic:1340,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:115,traffic:96,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:68,traffic:620,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:64,traffic:81,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:62,traffic:44,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:58,traffic:453,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/lampServer/index.htm',hits:46,traffic:62,name:'index',ext:'htm',relurl:'inTec/lampServer/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:40,traffic:80,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:39,traffic:497,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:36,traffic:58,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:34,traffic:64,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:30,traffic:119,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:27,traffic:61,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:25,traffic:280,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:24,traffic:43,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/index.htm',hits:24,traffic:19,name:'index',ext:'htm',relurl:'dds.arc/new-site/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:23,traffic:106,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/maxlength.htm',hits:20,traffic:61,name:'maxlength',ext:'htm',relurl:'dzLib/maxlength.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:20,traffic:78,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:19,traffic:44,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:17,traffic:177,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/index.htm',hits:16,traffic:28,name:'index',ext:'htm',relurl:'google/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:15,traffic:293,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:15,traffic:48,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:15,traffic:27,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:13,traffic:72,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:12,traffic:20,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:12,traffic:13,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:12,traffic:17,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:11,traffic:28,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:11,traffic:77,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:11,traffic:56,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:10,traffic:22,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:10,traffic:21,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:10,traffic:47,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:10,traffic:4,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:10,traffic:5,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:9,traffic:6,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:9,traffic:50,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:9,traffic:17,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:9,traffic:63,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/nl.htm',hits:9,traffic:21,name:'nl',ext:'htm',relurl:'google/nl.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:9,traffic:31,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_text-flow.htm',hits:8,traffic:26,name:'_text-flow',ext:'htm',relurl:'inTec/_text-flow.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/en.htm',hits:8,traffic:22,name:'en',ext:'htm',relurl:'google/en.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:8,traffic:7,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:8,traffic:27,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/entrance.htm',hits:8,traffic:10,name:'entrance',ext:'htm',relurl:'dds.arc/miniwebventure/entrance.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:8,traffic:13,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/tabe/index.htm',hits:8,traffic:2,name:'index',ext:'htm',relurl:'dds.arc/tabe/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:7,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:7,traffic:19,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:7,traffic:16,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:7,traffic:13,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:7,traffic:41,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:7,traffic:60,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:7,traffic:9,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:7,traffic:31,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:7,traffic:22,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:7,traffic:9,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:7,traffic:11,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:6,traffic:27,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:6,traffic:24,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:6,traffic:3,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nt.html',hits:6,traffic:7,name:'nt',ext:'htm',relurl:'dds.arc/Australia/nt.html'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:6,traffic:28,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:6,traffic:16,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:6,traffic:43,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery.html',hits:6,traffic:12,name:'photoGallery',ext:'htm',relurl:'dds.arc/Australia/photoGallery.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:5,traffic:29,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:5,traffic:8,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:5,traffic:32,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:5,traffic:26,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:5,traffic:7,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:5,traffic:1,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:5,traffic:7,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:5,traffic:11,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:5,traffic:4,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/contact.html',hits:5,traffic:4,name:'contact',ext:'htm',relurl:'dds.arc/contact.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/zanstra/index.htm',hits:4,traffic:3,name:'index',ext:'htm',relurl:'dds.arc/zanstra/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:4,traffic:3,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/go_down.htm',hits:4,traffic:2,name:'go_down',ext:'htm',relurl:'dds.arc/miniwebventure/go_down.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nz1.html',hits:4,traffic:0,name:'nz1',ext:'htm',relurl:'dds.arc/Australia/nz1.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:4,traffic:16,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/cch.html',hits:4,traffic:0,name:'cch',ext:'htm',relurl:'dds.arc/Australia/cch.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/medkit.htm',hits:4,traffic:1,name:'medkit',ext:'htm',relurl:'dds.arc/miniwebventure/icons/medkit.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/money.htm',hits:4,traffic:1,name:'money',ext:'htm',relurl:'dds.arc/miniwebventure/icons/money.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/goingdown.htm',hits:4,traffic:1,name:'goingdown',ext:'htm',relurl:'dds.arc/miniwebventure/goingdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/halleast.htm',hits:4,traffic:2,name:'halleast',ext:'htm',relurl:'dds.arc/miniwebventure/halleast.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/looknote.htm',hits:4,traffic:4,name:'looknote',ext:'htm',relurl:'dds.arc/miniwebventure/looknote.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/olrik.html',hits:4,traffic:4,name:'olrik',ext:'htm',relurl:'dds.arc/olrik.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/note.htm',hits:4,traffic:1,name:'note',ext:'htm',relurl:'dds.arc/miniwebventure/icons/note.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_template.htm',hits:4,traffic:4,name:'_template',ext:'htm',relurl:'jsPrj/_template.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:4,traffic:16,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/empty.htm',hits:4,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/icons/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/muziek/piano.htm',hits:4,traffic:0,name:'piano',ext:'htm',relurl:'dds.arc/muziek/piano.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_north.htm',hits:4,traffic:1,name:'all_north',ext:'htm',relurl:'dds.arc/miniwebventure/all_north.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:4,traffic:3,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:4,traffic:39,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/nrc20011213.htm',hits:4,traffic:0,name:'nrc20011213',ext:'htm',relurl:'nrc/nrc20011213.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:4,traffic:0,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/shower.htm',hits:4,traffic:2,name:'shower',ext:'htm',relurl:'dds.arc/miniwebventure/shower.htm'}
];
