/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2005_3=new Date(2005,5-1,3,21,43,14,805);
var stats_2005_3=[{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:269,traffic:4604,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:263,traffic:1839,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:227,traffic:1315,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:113,traffic:636,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:109,traffic:1010,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:71,traffic:516,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:63,traffic:54,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:55,traffic:69,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:46,traffic:585,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:39,traffic:63,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:33,traffic:630,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/maxlength.htm',hits:33,traffic:80,name:'maxlength',ext:'htm',relurl:'dzLib/maxlength.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:31,traffic:23,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:31,traffic:123,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:23,traffic:98,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:23,traffic:18,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:19,traffic:31,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:19,traffic:26,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:18,traffic:80,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:16,traffic:35,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:15,traffic:30,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:14,traffic:39,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:13,traffic:7,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:13,traffic:5,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:12,traffic:18,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:11,traffic:105,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:11,traffic:88,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:11,traffic:19,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:11,traffic:23,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:11,traffic:19,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:10,traffic:37,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:9,traffic:15,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:9,traffic:21,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:9,traffic:4,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:8,traffic:43,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:8,traffic:30,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:8,traffic:6,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:8,traffic:28,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:8,traffic:21,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:8,traffic:9,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:7,traffic:15,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:7,traffic:21,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:7,traffic:31,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:7,traffic:39,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:6,traffic:13,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:6,traffic:78,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:6,traffic:28,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:6,traffic:5,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:5,traffic:16,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:5,traffic:26,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:5,traffic:11,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:5,traffic:3,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/index.htm',hits:4,traffic:5,name:'index',ext:'htm',relurl:'dds.arc/new-site/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/_template.htm',hits:4,traffic:1,name:'_template',ext:'htm',relurl:'_template.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:4,traffic:1,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:4,traffic:12,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:3,traffic:3,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:3,traffic:13,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/vierhoek.html',hits:3,traffic:4,name:'vierhoek',ext:'htm',relurl:'dds.arc/vierhoek.html'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:3,traffic:2,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:3,traffic:9,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:3,traffic:12,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:3,traffic:2,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:3,traffic:30,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/route.html',hits:3,traffic:0,name:'route',ext:'htm',relurl:'dds.arc/route.html'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:2,traffic:0,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:2,traffic:11,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:2,traffic:33,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-Apr2004.html',hits:2,traffic:87,name:'stats-Apr2004',ext:'htm',relurl:'stats-Apr2004.html'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'inTec/safariIdea/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:2,traffic:8,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:2,traffic:13,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:2,traffic:11,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:2,traffic:16,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum2004.htm',hits:2,traffic:0,name:'stats-cum2004',ext:'htm',relurl:'stats-cum2004.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/jsTools.htm',hits:2,traffic:0,name:'jsTools',ext:'htm',relurl:'dds.arc/jsTools.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/html-edit.htm',hits:2,traffic:0,name:'html-edit',ext:'htm',relurl:'jsPrj/html-edit.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:2,traffic:9,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:2,traffic:4,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_htmlMail.htm',hits:1,traffic:7,name:'_htmlMail',ext:'htm',relurl:'inTec/_htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:1,traffic:6,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:1,traffic:0,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/nrc20011009.htm',hits:1,traffic:18,name:'nrc20011009',ext:'htm',relurl:'nrc/nrc20011009.htm'}
,{url:'http://www.xs4all.nl/~zanstra/img/index.htm',hits:1,traffic:0,name:'index',ext:'htm',relurl:'img/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:1,traffic:5,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:1,traffic:0,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
];
