/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2004_7=new Date(2004,9-1,1,20,30,53,718);
var stats_2004_7=[{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:329,traffic:5546,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:226,traffic:1676,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:197,traffic:1262,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:145,traffic:106,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:141,traffic:903,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:95,traffic:904,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:77,traffic:58,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:51,traffic:548,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:37,traffic:294,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:32,traffic:119,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:30,traffic:61,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:28,traffic:37,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:23,traffic:340,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:19,traffic:100,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:19,traffic:30,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:18,traffic:47,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:16,traffic:65,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:16,traffic:138,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:16,traffic:24,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:14,traffic:27,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:13,traffic:42,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:12,traffic:20,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:12,traffic:11,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:11,traffic:3,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:11,traffic:26,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/doekman/index.htm',hits:11,traffic:69,name:'index',ext:'htm',relurl:'dds.arc/doekman/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:10,traffic:39,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:10,traffic:21,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:9,traffic:7,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:9,traffic:27,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_south.htm',hits:8,traffic:5,name:'all_south',ext:'htm',relurl:'dds.arc/miniwebventure/all_south.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:8,traffic:38,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:8,traffic:19,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:8,traffic:57,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:8,traffic:55,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:8,traffic:39,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:8,traffic:4,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:8,traffic:14,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:7,traffic:22,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:7,traffic:38,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/lampServer/index.htm',hits:6,traffic:13,name:'index',ext:'htm',relurl:'inTec/lampServer/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:6,traffic:11,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:6,traffic:23,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:6,traffic:38,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:6,traffic:3,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:6,traffic:37,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:5,traffic:8,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:5,traffic:28,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:5,traffic:23,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:5,traffic:22,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:5,traffic:40,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:5,traffic:58,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:5,traffic:23,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/tabe/index.htm',hits:5,traffic:2,name:'index',ext:'htm',relurl:'dds.arc/tabe/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:4,traffic:66,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:4,traffic:5,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:4,traffic:3,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:4,traffic:22,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:4,traffic:203,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/jsTools.htm',hits:4,traffic:25,name:'jsTools',ext:'htm',relurl:'dds.arc/jsTools.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:4,traffic:13,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:4,traffic:7,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:4,traffic:9,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/index.htm',hits:4,traffic:2,name:'index',ext:'htm',relurl:'inTec/safariIdea/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:4,traffic:8,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:4,traffic:11,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:3,traffic:12,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:3,traffic:14,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-Apr2004.html',hits:3,traffic:87,name:'stats-Apr2004',ext:'htm',relurl:'stats-Apr2004.html'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:3,traffic:14,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/halleast.htm',hits:3,traffic:2,name:'halleast',ext:'htm',relurl:'dds.arc/miniwebventure/halleast.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/entrance.htm',hits:3,traffic:4,name:'entrance',ext:'htm',relurl:'dds.arc/miniwebventure/entrance.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum2003.htm',hits:3,traffic:11,name:'stats-cum2003',ext:'htm',relurl:'stats-cum2003.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nz1.html',hits:2,traffic:7,name:'nz1',ext:'htm',relurl:'dds.arc/Australia/nz1.html'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:2,traffic:8,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:2,traffic:0,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/nrc20011213.htm',hits:2,traffic:32,name:'nrc20011213',ext:'htm',relurl:'nrc/nrc20011213.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:2,traffic:8,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:2,traffic:5,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:2,traffic:0,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:2,traffic:13,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_template.htm',hits:2,traffic:1,name:'_template',ext:'htm',relurl:'jsPrj/_template.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:2,traffic:4,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/muziek/piano.htm',hits:2,traffic:9,name:'piano',ext:'htm',relurl:'dds.arc/muziek/piano.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:1,traffic:8,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/olrik.html',hits:1,traffic:4,name:'olrik',ext:'htm',relurl:'dds.arc/olrik.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/contact.html',hits:1,traffic:0,name:'contact',ext:'htm',relurl:'dds.arc/contact.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery2.html',hits:1,traffic:0,name:'photoGallery2',ext:'htm',relurl:'dds.arc/Australia/photoGallery2.html'}
];
