/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2003_9=new Date(2003,11-1,1,14,28,57,140);
var stats_2003_9=[{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:604,traffic:6670,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:453,traffic:2931,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:357,traffic:1951,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:129,traffic:969,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:108,traffic:1158,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:88,traffic:517,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:75,traffic:51,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:45,traffic:516,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:37,traffic:31,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:37,traffic:161,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:35,traffic:329,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:33,traffic:158,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:31,traffic:46,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:30,traffic:52,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:26,traffic:46,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:24,traffic:27,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:24,traffic:5,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:22,traffic:16,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:19,traffic:21,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:17,traffic:82,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:17,traffic:109,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:16,traffic:84,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:16,traffic:17,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:15,traffic:42,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:15,traffic:18,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:15,traffic:9,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:14,traffic:45,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:14,traffic:100,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:14,traffic:7,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:13,traffic:152,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:13,traffic:69,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:12,traffic:23,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:11,traffic:23,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:11,traffic:17,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:11,traffic:26,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:10,traffic:31,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:10,traffic:111,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:9,traffic:37,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:9,traffic:17,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:9,traffic:39,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:8,traffic:27,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:8,traffic:59,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:8,traffic:25,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:7,traffic:27,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:7,traffic:39,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:6,traffic:43,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:6,traffic:23,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:5,traffic:6,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nt.html',hits:5,traffic:11,name:'nt',ext:'htm',relurl:'dds.arc/Australia/nt.html'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:5,traffic:28,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:5,traffic:39,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:4,traffic:5,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/note.htm',hits:4,traffic:1,name:'note',ext:'htm',relurl:'dds.arc/miniwebventure/icons/note.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:4,traffic:16,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:4,traffic:9,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:4,traffic:15,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/doekman/index.htm',hits:4,traffic:25,name:'index',ext:'htm',relurl:'dds.arc/doekman/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_text-flow.htm',hits:4,traffic:16,name:'_text-flow',ext:'htm',relurl:'inTec/_text-flow.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/cch.html',hits:4,traffic:9,name:'cch',ext:'htm',relurl:'dds.arc/Australia/cch.html'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index_.htm',hits:4,traffic:7,name:'index_',ext:'htm',relurl:'fotos/index_.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:4,traffic:16,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:4,traffic:19,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:3,traffic:14,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/capeyork.html',hits:3,traffic:7,name:'capeyork',ext:'htm',relurl:'dds.arc/Australia/capeyork.html'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:3,traffic:9,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/helpItems.htm',hits:3,traffic:6,name:'helpItems',ext:'htm',relurl:'inTec/httpTutor/helpItems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:3,traffic:4,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:3,traffic:135,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nz1.html',hits:3,traffic:7,name:'nz1',ext:'htm',relurl:'dds.arc/Australia/nz1.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/zanstra/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/zanstra/index.htm'}
];
