/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2004_4=new Date(2004,6-1,1,22,5,46,571);
var stats_2004_4=[{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:336,traffic:4899,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:199,traffic:1322,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:193,traffic:1497,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:137,traffic:832,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:85,traffic:778,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:84,traffic:70,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:64,traffic:40,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:52,traffic:483,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:33,traffic:127,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:33,traffic:410,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:28,traffic:500,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:21,traffic:45,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:21,traffic:31,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:19,traffic:35,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:17,traffic:88,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:17,traffic:63,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:16,traffic:21,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:14,traffic:139,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:13,traffic:58,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:11,traffic:30,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:11,traffic:3,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:11,traffic:28,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:11,traffic:16,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:10,traffic:12,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:10,traffic:21,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:10,traffic:117,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:9,traffic:45,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:9,traffic:24,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:9,traffic:33,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:8,traffic:44,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:7,traffic:32,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:7,traffic:39,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:6,traffic:3,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:6,traffic:7,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:6,traffic:38,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:6,traffic:6,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:5,traffic:16,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:5,traffic:10,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:5,traffic:13,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:5,traffic:36,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:5,traffic:23,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:5,traffic:2,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:5,traffic:19,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:5,traffic:16,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:5,traffic:8,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:5,traffic:39,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:4,traffic:22,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:4,traffic:18,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_text-flow.htm',hits:4,traffic:11,name:'_text-flow',ext:'htm',relurl:'inTec/_text-flow.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/index.htm',hits:4,traffic:2,name:'index',ext:'htm',relurl:'inTec/safariIdea/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:4,traffic:2,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:4,traffic:66,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:4,traffic:22,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:4,traffic:25,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:4,traffic:2,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:3,traffic:16,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/olrik.html',hits:3,traffic:11,name:'olrik',ext:'htm',relurl:'dds.arc/olrik.html'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:3,traffic:21,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:3,traffic:24,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/muziek/piano.htm',hits:3,traffic:27,name:'piano',ext:'htm',relurl:'dds.arc/muziek/piano.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:3,traffic:7,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:3,traffic:37,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:3,traffic:14,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:3,traffic:68,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:3,traffic:22,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:3,traffic:6,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:3,traffic:14,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:3,traffic:6,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/div_onclick.htm',hits:2,traffic:1,name:'div_onclick',ext:'htm',relurl:'dzLib/event/div_onclick.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_htmlMail.htm',hits:2,traffic:14,name:'_htmlMail',ext:'htm',relurl:'inTec/_htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:2,traffic:8,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:2,traffic:9,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:2,traffic:3,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:2,traffic:4,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:2,traffic:2,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:2,traffic:4,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/index.htm',hits:2,traffic:3,name:'index',ext:'htm',relurl:'dzLib/event/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:1,traffic:0,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/moz_event.htm',hits:1,traffic:1,name:'moz_event',ext:'htm',relurl:'dzLib/event/moz_event.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-Apr2004.html',hits:1,traffic:43,name:'stats-Apr2004',ext:'htm',relurl:'stats-Apr2004.html'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:1,traffic:1,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/detectBubble.htm',hits:1,traffic:4,name:'detectBubble',ext:'htm',relurl:'dzLib/event/detectBubble.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:1,traffic:6,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
];
