/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2003_2=new Date(2003,5-1,24,23,8,40,997);
var stats_2003_2=[{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:304,traffic:1782,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:180,traffic:623,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:120,traffic:962,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:83,traffic:595,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/statistics.html',hits:40,traffic:565,name:'statistics',ext:'htm',relurl:'statistics.html'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:39,traffic:502,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:38,traffic:146,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index_.htm',hits:36,traffic:243,name:'index_',ext:'htm',relurl:'fotos/index_.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:35,traffic:197,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:34,traffic:47,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:32,traffic:103,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:30,traffic:87,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:30,traffic:281,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:30,traffic:316,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:30,traffic:96,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:29,traffic:53,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:28,traffic:144,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:26,traffic:60,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:25,traffic:56,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:25,traffic:65,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:24,traffic:60,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:21,traffic:171,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:21,traffic:18,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:21,traffic:7,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:19,traffic:59,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:19,traffic:136,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:18,traffic:41,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:17,traffic:17,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:17,traffic:72,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:17,traffic:78,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:17,traffic:14,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:16,traffic:29,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:16,traffic:58,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:15,traffic:11,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:14,traffic:541,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:14,traffic:49,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:13,traffic:52,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:12,traffic:26,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:11,traffic:12,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:11,traffic:43,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:11,traffic:8,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:11,traffic:14,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:11,traffic:10,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:11,traffic:24,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:10,traffic:19,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:10,traffic:16,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:9,traffic:23,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/zanstra/index.htm',hits:9,traffic:3,name:'index',ext:'htm',relurl:'dds.arc/zanstra/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:9,traffic:14,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:9,traffic:26,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:8,traffic:17,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/doekman/index.htm',hits:8,traffic:19,name:'index',ext:'htm',relurl:'dds.arc/doekman/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:8,traffic:7,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:8,traffic:48,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/index.htm',hits:7,traffic:8,name:'index',ext:'htm',relurl:'dds.arc/miniwebventure/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:5,traffic:16,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:4,traffic:5,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:3,traffic:9,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:3,traffic:15,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/empty.htm',hits:3,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/icons/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/default.htm',hits:3,traffic:7,name:'default',ext:'htm',relurl:'dds.arc/new-site/default.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:3,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/olrik.html',hits:3,traffic:11,name:'olrik',ext:'htm',relurl:'dds.arc/olrik.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/cch.html',hits:3,traffic:9,name:'cch',ext:'htm',relurl:'dds.arc/Australia/cch.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/muziek/piano.htm',hits:3,traffic:27,name:'piano',ext:'htm',relurl:'dds.arc/muziek/piano.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nz1.html',hits:3,traffic:11,name:'nz1',ext:'htm',relurl:'dds.arc/Australia/nz1.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/doeke.htm',hits:3,traffic:3,name:'doeke',ext:'htm',relurl:'dds.arc/miniwebventure/doeke.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:3,traffic:3,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/jsTools.htm',hits:3,traffic:19,name:'jsTools',ext:'htm',relurl:'dds.arc/jsTools.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/vierhoek.html',hits:3,traffic:12,name:'vierhoek',ext:'htm',relurl:'dds.arc/vierhoek.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/tabe/index.htm',hits:3,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/tabe/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/computer.htm',hits:2,traffic:1,name:'computer',ext:'htm',relurl:'dds.arc/miniwebventure/icons/computer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/koop.htm',hits:2,traffic:1,name:'koop',ext:'htm',relurl:'dds.arc/miniwebventure/koop.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/capeyork.html',hits:2,traffic:7,name:'capeyork',ext:'htm',relurl:'dds.arc/Australia/capeyork.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_south.htm',hits:2,traffic:1,name:'all_south',ext:'htm',relurl:'dds.arc/miniwebventure/all_south.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/halleast.htm',hits:2,traffic:1,name:'halleast',ext:'htm',relurl:'dds.arc/miniwebventure/halleast.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/toilet.htm',hits:2,traffic:1,name:'toilet',ext:'htm',relurl:'dds.arc/miniwebventure/toilet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/note.htm',hits:2,traffic:1,name:'note',ext:'htm',relurl:'dds.arc/miniwebventure/icons/note.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:2,traffic:4,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:2,traffic:5,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/shower.htm',hits:2,traffic:1,name:'shower',ext:'htm',relurl:'dds.arc/miniwebventure/shower.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/msg_1.htm',hits:2,traffic:1,name:'msg_1',ext:'htm',relurl:'dds.arc/miniwebventure/msg_1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery.html',hits:2,traffic:12,name:'photoGallery',ext:'htm',relurl:'dds.arc/Australia/photoGallery.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_north.htm',hits:2,traffic:1,name:'all_north',ext:'htm',relurl:'dds.arc/miniwebventure/all_north.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/hallwest.htm',hits:2,traffic:1,name:'hallwest',ext:'htm',relurl:'dds.arc/miniwebventure/hallwest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nt.html',hits:2,traffic:7,name:'nt',ext:'htm',relurl:'dds.arc/Australia/nt.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_middle.htm',hits:2,traffic:2,name:'all_middle',ext:'htm',relurl:'dds.arc/miniwebventure/all_middle.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/looknote.htm',hits:2,traffic:2,name:'looknote',ext:'htm',relurl:'dds.arc/miniwebventure/looknote.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/route.html',hits:2,traffic:5,name:'route',ext:'htm',relurl:'dds.arc/route.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/inventory.htm',hits:2,traffic:1,name:'inventory',ext:'htm',relurl:'dds.arc/miniwebventure/icons/inventory.htm'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:2,traffic:4,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/kitchen.htm',hits:2,traffic:1,name:'kitchen',ext:'htm',relurl:'dds.arc/miniwebventure/kitchen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/contact.html',hits:2,traffic:7,name:'contact',ext:'htm',relurl:'dds.arc/contact.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery2.html',hits:2,traffic:12,name:'photoGallery2',ext:'htm',relurl:'dds.arc/Australia/photoGallery2.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/go_down.htm',hits:2,traffic:1,name:'go_down',ext:'htm',relurl:'dds.arc/miniwebventure/go_down.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/helpItems.htm',hits:1,traffic:0,name:'helpItems',ext:'htm',relurl:'inTec/httpTutor/helpItems.htm'}
];
