/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2004_6=new Date(2004,8-1,3,0,24,13,598);
var stats_2004_6=[{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:263,traffic:3979,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:160,traffic:983,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:143,traffic:1089,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:106,traffic:73,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:79,traffic:747,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:53,traffic:338,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:52,traffic:275,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:48,traffic:35,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:42,traffic:527,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:41,traffic:409,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:36,traffic:124,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:24,traffic:35,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:23,traffic:48,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:19,traffic:52,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:16,traffic:280,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:15,traffic:7,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:15,traffic:52,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:15,traffic:22,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:14,traffic:16,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:13,traffic:27,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:12,traffic:34,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:10,traffic:23,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:9,traffic:11,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:9,traffic:32,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:9,traffic:8,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:8,traffic:13,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:8,traffic:26,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:8,traffic:14,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:7,traffic:33,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:7,traffic:8,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:7,traffic:82,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:6,traffic:40,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:6,traffic:11,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:6,traffic:16,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:6,traffic:5,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:6,traffic:39,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:6,traffic:100,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:6,traffic:16,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:5,traffic:15,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:5,traffic:10,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:5,traffic:28,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:5,traffic:9,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:5,traffic:32,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/lampServer/index.htm',hits:5,traffic:11,name:'index',ext:'htm',relurl:'inTec/lampServer/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:5,traffic:24,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:4,traffic:12,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:4,traffic:26,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:4,traffic:2,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:4,traffic:6,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:4,traffic:16,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/index.htm',hits:4,traffic:2,name:'index',ext:'htm',relurl:'inTec/safariIdea/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:4,traffic:22,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:3,traffic:12,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:3,traffic:37,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:3,traffic:1,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:3,traffic:14,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:2,traffic:7,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:2,traffic:9,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:2,traffic:6,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:2,traffic:13,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:2,traffic:14,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_text-flow.htm',hits:2,traffic:5,name:'_text-flow',ext:'htm',relurl:'inTec/_text-flow.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:2,traffic:3,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum2003.htm',hits:2,traffic:6,name:'stats-cum2003',ext:'htm',relurl:'stats-cum2003.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:2,traffic:3,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:2,traffic:9,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_htmlMail.htm',hits:2,traffic:14,name:'_htmlMail',ext:'htm',relurl:'inTec/_htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:2,traffic:0,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/index.htm',hits:2,traffic:2,name:'index',ext:'htm',relurl:'dds.arc/miniwebventure/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/tabe/index.htm',hits:2,traffic:0,name:'index',ext:'htm',relurl:'dds.arc/tabe/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:1,traffic:8,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/doeke.htm',hits:1,traffic:1,name:'doeke',ext:'htm',relurl:'dds.arc/miniwebventure/doeke.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm#kennify/index.htm',hits:1,traffic:18,name:'index',ext:'htm',relurl:'logs/jsLog.htm#kennify/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:1,traffic:5,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:1,traffic:8,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:1,traffic:0,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:1,traffic:0,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/empty.htm',hits:1,traffic:0,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/icons/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:1,traffic:7,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/moz_event.htm',hits:1,traffic:1,name:'moz_event',ext:'htm',relurl:'dzLib/event/moz_event.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/entrance.htm',hits:1,traffic:1,name:'entrance',ext:'htm',relurl:'dds.arc/miniwebventure/entrance.htm'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:1,traffic:2,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/msg_1.htm',hits:1,traffic:1,name:'msg_1',ext:'htm',relurl:'dds.arc/miniwebventure/msg_1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/inventory.htm',hits:1,traffic:0,name:'inventory',ext:'htm',relurl:'dds.arc/miniwebventure/icons/inventory.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:1,traffic:3,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:1,traffic:2,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/zanstra/index.htm',hits:1,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/zanstra/index.htm'}
];
