/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2005_10=new Date(2005,12-1,26,17,59,22,5);
var stats_2005_10=[{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:377,traffic:2925,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:286,traffic:1959,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:280,traffic:2484,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:175,traffic:670,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:135,traffic:109,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:82,traffic:491,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:81,traffic:754,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:75,traffic:97,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/maxlength.htm',hits:72,traffic:204,name:'maxlength',ext:'htm',relurl:'dzLib/maxlength.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:64,traffic:701,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:63,traffic:351,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog-2004.htm',hits:60,traffic:1020,name:'jsLog-2004',ext:'htm',relurl:'logs/jsLog-2004.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:57,traffic:117,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:54,traffic:41,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:47,traffic:323,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/lampServer/index.htm',hits:47,traffic:71,name:'index',ext:'htm',relurl:'inTec/lampServer/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:44,traffic:315,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:42,traffic:833,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:42,traffic:170,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:40,traffic:251,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:38,traffic:62,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:37,traffic:130,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/index.htm',hits:37,traffic:30,name:'index',ext:'htm',relurl:'dds.arc/new-site/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/chknav.htm',hits:36,traffic:88,name:'chknav',ext:'htm',relurl:'dzLib/chknav.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:35,traffic:96,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:32,traffic:182,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/index.htm',hits:31,traffic:50,name:'index',ext:'htm',relurl:'google/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:31,traffic:42,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:30,traffic:66,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:30,traffic:134,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:29,traffic:130,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:27,traffic:42,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:27,traffic:45,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:27,traffic:67,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:26,traffic:41,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:26,traffic:45,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:26,traffic:10,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005.html',hits:23,traffic:99,name:'Safier2005',ext:'htm',relurl:'Safier2005/Safier2005.html'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:22,traffic:113,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:22,traffic:29,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:18,traffic:39,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:18,traffic:27,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:18,traffic:31,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:18,traffic:32,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:18,traffic:39,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:17,traffic:39,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:16,traffic:17,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:16,traffic:14,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:14,traffic:7,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:14,traffic:81,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:14,traffic:100,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:13,traffic:43,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:12,traffic:81,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:12,traffic:9,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/doekman/index.htm',hits:12,traffic:40,name:'index',ext:'htm',relurl:'dds.arc/doekman/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:11,traffic:46,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:11,traffic:1,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:11,traffic:77,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_jsListSearchSpeedTest.htm',hits:11,traffic:10,name:'_jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/_jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:11,traffic:23,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:11,traffic:23,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:11,traffic:7,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/en.htm',hits:10,traffic:22,name:'en',ext:'htm',relurl:'google/en.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc/dzLib/index.htm',hits:10,traffic:8,name:'index',ext:'htm',relurl:'arc/dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:10,traffic:15,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:9,traffic:32,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:9,traffic:19,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image0.html',hits:9,traffic:3,name:'Image0',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image0.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:9,traffic:20,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:9,traffic:93,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:9,traffic:150,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:9,traffic:23,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:9,traffic:12,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:8,traffic:9,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:8,traffic:9,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:8,traffic:16,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:8,traffic:50,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/nrc20011213.htm',hits:7,traffic:49,name:'nrc20011213',ext:'htm',relurl:'nrc/nrc20011213.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index_.htm',hits:7,traffic:35,name:'index_',ext:'htm',relurl:'fotos/index_.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image18.html',hits:7,traffic:3,name:'Image18',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image18.html'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:6,traffic:18,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:6,traffic:7,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:6,traffic:3,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:6,traffic:24,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_text-flow.htm',hits:6,traffic:10,name:'_text-flow',ext:'htm',relurl:'inTec/_text-flow.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:6,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/empty.htm',hits:6,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/icons/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image6.html',hits:5,traffic:2,name:'Image6',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image6.html'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:5,traffic:8,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:5,traffic:7,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image1.html',hits:5,traffic:2,name:'Image1',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image1.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:5,traffic:0,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:5,traffic:32,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image12.html',hits:5,traffic:2,name:'Image12',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image12.html'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/var-inspect.html',hits:5,traffic:19,name:'var-inspect',ext:'htm',relurl:'dzLib/var-inspect.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image7.html',hits:5,traffic:2,name:'Image7',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image7.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/entrance.htm',hits:5,traffic:5,name:'entrance',ext:'htm',relurl:'dds.arc/miniwebventure/entrance.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image11.html',hits:5,traffic:2,name:'Image11',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image11.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image9.html',hits:5,traffic:2,name:'Image9',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image9.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image5.html',hits:5,traffic:2,name:'Image5',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image5.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image10.html',hits:5,traffic:2,name:'Image10',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image10.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image4.html',hits:5,traffic:2,name:'Image4',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image4.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image13.html',hits:5,traffic:2,name:'Image13',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image13.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image14.html',hits:5,traffic:2,name:'Image14',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image14.html'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image8.html',hits:5,traffic:2,name:'Image8',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image8.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:5,traffic:2,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/Safier2005/Safier2005-Pages/Image2.html',hits:5,traffic:2,name:'Image2',ext:'htm',relurl:'Safier2005/Safier2005-Pages/Image2.html'}
];
