/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2003_6=new Date(2003,8-1,4,23,18,25,103);
var stats_2003_6=[{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:376,traffic:2116,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:314,traffic:1732,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:82,traffic:594,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:51,traffic:288,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:51,traffic:694,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:31,traffic:131,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:30,traffic:112,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:27,traffic:68,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:24,traffic:80,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:22,traffic:222,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:22,traffic:124,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:22,traffic:171,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:21,traffic:27,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:21,traffic:12,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:20,traffic:27,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:20,traffic:52,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:18,traffic:8,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:17,traffic:107,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:15,traffic:18,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:15,traffic:7,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:14,traffic:38,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:13,traffic:26,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:13,traffic:6,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:13,traffic:40,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:11,traffic:50,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:7,traffic:22,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:7,traffic:8,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:7,traffic:9,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:6,traffic:39,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:6,traffic:38,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:6,traffic:12,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:5,traffic:23,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:5,traffic:24,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:5,traffic:338,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:5,traffic:11,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:5,traffic:3,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:4,traffic:14,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:4,traffic:11,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:4,traffic:6,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:4,traffic:12,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:4,traffic:18,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:4,traffic:8,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:4,traffic:5,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:3,traffic:14,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:3,traffic:23,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:3,traffic:7,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:3,traffic:4,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:3,traffic:7,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:3,traffic:19,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/doekman/index.htm',hits:3,traffic:0,name:'index',ext:'htm',relurl:'dds.arc/doekman/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/medkit.htm',hits:2,traffic:0,name:'medkit',ext:'htm',relurl:'dds.arc/miniwebventure/icons/medkit.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:2,traffic:8,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/zanstra/index.htm',hits:2,traffic:0,name:'index',ext:'htm',relurl:'dds.arc/zanstra/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/index.htm',hits:2,traffic:5,name:'index',ext:'htm',relurl:'dds.arc/miniwebventure/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:2,traffic:10,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:2,traffic:2,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/inventory.htm',hits:2,traffic:1,name:'inventory',ext:'htm',relurl:'dds.arc/miniwebventure/icons/inventory.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:2,traffic:9,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/nrc20011213.htm',hits:2,traffic:32,name:'nrc20011213',ext:'htm',relurl:'nrc/nrc20011213.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/olrik.html',hits:2,traffic:4,name:'olrik',ext:'htm',relurl:'dds.arc/olrik.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:2,traffic:14,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:2,traffic:13,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
];
