/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2005_1=new Date(2005,3-1,2,20,38,11,350);
var stats_2005_1=[{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:402,traffic:2919,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:256,traffic:4005,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:215,traffic:1263,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:117,traffic:97,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:93,traffic:906,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:92,traffic:799,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:66,traffic:776,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:65,traffic:241,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:48,traffic:75,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:46,traffic:34,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:46,traffic:180,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:42,traffic:52,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:34,traffic:136,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/maxlength.htm',hits:34,traffic:96,name:'maxlength',ext:'htm',relurl:'dzLib/maxlength.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:33,traffic:51,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:31,traffic:31,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:31,traffic:115,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:30,traffic:150,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:27,traffic:48,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:27,traffic:85,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:25,traffic:497,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:23,traffic:21,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:22,traffic:210,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:18,traffic:47,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:17,traffic:39,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:16,traffic:38,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:16,traffic:79,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:16,traffic:33,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/lampServer/index.htm',hits:16,traffic:28,name:'index',ext:'htm',relurl:'inTec/lampServer/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:15,traffic:54,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:15,traffic:6,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:14,traffic:21,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:13,traffic:71,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:13,traffic:17,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:13,traffic:77,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:13,traffic:52,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:13,traffic:17,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:12,traffic:7,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:12,traffic:30,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:11,traffic:41,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:11,traffic:19,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:11,traffic:26,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:11,traffic:9,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:10,traffic:15,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:10,traffic:34,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:9,traffic:24,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:9,traffic:7,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:9,traffic:39,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:9,traffic:78,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:9,traffic:5,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:8,traffic:42,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:7,traffic:8,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:7,traffic:10,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:7,traffic:31,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/index.htm',hits:7,traffic:22,name:'index',ext:'htm',relurl:'dds.arc/Australia/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/index.htm',hits:6,traffic:3,name:'index',ext:'htm',relurl:'inTec/safariIdea/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:6,traffic:12,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:6,traffic:14,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:6,traffic:67,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/index.htm',hits:6,traffic:8,name:'index',ext:'htm',relurl:'dds.arc/miniwebventure/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index_.htm',hits:5,traffic:0,name:'index_',ext:'htm',relurl:'fotos/index_.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:5,traffic:29,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:5,traffic:4,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:5,traffic:2,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:5,traffic:17,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_text-flow.htm',hits:5,traffic:26,name:'_text-flow',ext:'htm',relurl:'inTec/_text-flow.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:5,traffic:17,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:5,traffic:22,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:5,traffic:7,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:5,traffic:7,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:4,traffic:2,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:4,traffic:6,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:4,traffic:0,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:4,traffic:16,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:4,traffic:14,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:4,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:4,traffic:2,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery.html',hits:3,traffic:0,name:'photoGallery',ext:'htm',relurl:'dds.arc/Australia/photoGallery.html'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:3,traffic:5,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:3,traffic:7,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:3,traffic:8,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:3,traffic:20,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:3,traffic:4,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/_template.htm',hits:3,traffic:1,name:'_template',ext:'htm',relurl:'_template.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/msg_1.htm',hits:3,traffic:2,name:'msg_1',ext:'htm',relurl:'dds.arc/miniwebventure/msg_1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-Apr2004.html',hits:3,traffic:87,name:'stats-Apr2004',ext:'htm',relurl:'stats-Apr2004.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/empty.htm',hits:3,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/icons/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum2004.htm',hits:3,traffic:7,name:'stats-cum2004',ext:'htm',relurl:'stats-cum2004.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:3,traffic:68,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:3,traffic:7,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/zanstra/index.htm',hits:3,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/zanstra/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/doeke.htm',hits:3,traffic:2,name:'doeke',ext:'htm',relurl:'dds.arc/miniwebventure/doeke.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:3,traffic:4,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery2.html',hits:2,traffic:0,name:'photoGallery2',ext:'htm',relurl:'dds.arc/Australia/photoGallery2.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/new-site/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/jsTools.htm',hits:2,traffic:6,name:'jsTools',ext:'htm',relurl:'dds.arc/jsTools.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/inventory.htm',hits:2,traffic:1,name:'inventory',ext:'htm',relurl:'dds.arc/miniwebventure/icons/inventory.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/helpItems.htm',hits:2,traffic:4,name:'helpItems',ext:'htm',relurl:'inTec/httpTutor/helpItems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/doekman/index.htm',hits:2,traffic:13,name:'index',ext:'htm',relurl:'dds.arc/doekman/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/computer.htm',hits:2,traffic:0,name:'computer',ext:'htm',relurl:'dds.arc/miniwebventure/icons/computer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/vierhoek.html',hits:2,traffic:4,name:'vierhoek',ext:'htm',relurl:'dds.arc/vierhoek.html'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/nrc20011213.htm',hits:2,traffic:16,name:'nrc20011213',ext:'htm',relurl:'nrc/nrc20011213.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/hallwest.htm',hits:2,traffic:0,name:'hallwest',ext:'htm',relurl:'dds.arc/miniwebventure/hallwest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_htmlMail.htm',hits:2,traffic:14,name:'_htmlMail',ext:'htm',relurl:'inTec/_htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/olrik.html',hits:2,traffic:0,name:'olrik',ext:'htm',relurl:'dds.arc/olrik.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:2,traffic:0,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/capeyork.html',hits:2,traffic:0,name:'capeyork',ext:'htm',relurl:'dds.arc/Australia/capeyork.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_jsListSearchSpeedTest.htm',hits:2,traffic:0,name:'_jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/_jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/route.html',hits:2,traffic:0,name:'route',ext:'htm',relurl:'dds.arc/route.html'}
];
