/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2005_5=new Date(2005,9-1,6,22,9,35,625);
var stats_2005_5=[{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:443,traffic:3284,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:386,traffic:2738,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:297,traffic:5220,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:290,traffic:1482,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:103,traffic:863,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:101,traffic:85,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:71,traffic:835,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:69,traffic:578,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/maxlength.htm',hits:63,traffic:166,name:'maxlength',ext:'htm',relurl:'dzLib/maxlength.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:62,traffic:43,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:62,traffic:77,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/lampServer/index.htm',hits:41,traffic:64,name:'index',ext:'htm',relurl:'inTec/lampServer/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:36,traffic:86,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/index.htm',hits:29,traffic:43,name:'index',ext:'htm',relurl:'google/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:26,traffic:61,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/new-site/index.htm',hits:26,traffic:20,name:'index',ext:'htm',relurl:'dds.arc/new-site/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:25,traffic:131,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:24,traffic:98,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:23,traffic:405,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:23,traffic:189,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:23,traffic:37,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:22,traffic:47,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:22,traffic:39,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:20,traffic:29,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:20,traffic:17,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:19,traffic:91,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:19,traffic:70,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/editor.htm',hits:18,traffic:32,name:'editor',ext:'htm',relurl:'jsPrj/editor.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:18,traffic:73,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:17,traffic:39,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:17,traffic:59,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:16,traffic:22,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:16,traffic:83,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:15,traffic:22,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:14,traffic:65,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:14,traffic:63,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:13,traffic:46,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:13,traffic:57,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:12,traffic:51,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:11,traffic:71,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:11,traffic:20,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:11,traffic:19,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/nl.htm',hits:11,traffic:9,name:'nl',ext:'htm',relurl:'google/nl.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:10,traffic:22,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:10,traffic:5,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/google/en.htm',hits:9,traffic:16,name:'en',ext:'htm',relurl:'google/en.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:9,traffic:29,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:9,traffic:78,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:9,traffic:11,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:9,traffic:11,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:8,traffic:6,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:8,traffic:1,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:8,traffic:40,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:8,traffic:6,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:8,traffic:3,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/tabe/index.htm',hits:8,traffic:2,name:'index',ext:'htm',relurl:'dds.arc/tabe/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:7,traffic:26,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:7,traffic:3,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:7,traffic:22,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:7,traffic:10,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:6,traffic:4,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/empty.htm',hits:6,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:6,traffic:8,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:6,traffic:13,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:6,traffic:21,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_jsListSearchSpeedTest.htm',hits:6,traffic:4,name:'_jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/_jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:6,traffic:12,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/qs.htm',hits:6,traffic:16,name:'qs',ext:'htm',relurl:'dzLib/qs.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/empty.htm',hits:6,traffic:1,name:'empty',ext:'htm',relurl:'dds.arc/miniwebventure/icons/empty.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:6,traffic:9,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/doeke.htm',hits:6,traffic:3,name:'doeke',ext:'htm',relurl:'dds.arc/miniwebventure/doeke.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:6,traffic:14,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:6,traffic:7,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/index.htm',hits:6,traffic:8,name:'index',ext:'htm',relurl:'dds.arc/miniwebventure/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/shutdown.htm',hits:5,traffic:2,name:'shutdown',ext:'htm',relurl:'shutdown.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:5,traffic:5,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/medkit.htm',hits:5,traffic:0,name:'medkit',ext:'htm',relurl:'dds.arc/miniwebventure/icons/medkit.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:5,traffic:2,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:5,traffic:11,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:4,traffic:8,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:4,traffic:8,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:4,traffic:13,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:4,traffic:1,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/cch.html',hits:4,traffic:3,name:'cch',ext:'htm',relurl:'dds.arc/Australia/cch.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/key_lock.htm',hits:4,traffic:0,name:'key_lock',ext:'htm',relurl:'dds.arc/miniwebventure/icons/key_lock.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/halleast.htm',hits:4,traffic:0,name:'halleast',ext:'htm',relurl:'dds.arc/miniwebventure/halleast.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/looknote.htm',hits:4,traffic:0,name:'looknote',ext:'htm',relurl:'dds.arc/miniwebventure/looknote.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/capeyork.html',hits:4,traffic:4,name:'capeyork',ext:'htm',relurl:'dds.arc/Australia/capeyork.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nt.html',hits:4,traffic:4,name:'nt',ext:'htm',relurl:'dds.arc/Australia/nt.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/note.htm',hits:4,traffic:0,name:'note',ext:'htm',relurl:'dds.arc/miniwebventure/icons/note.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:4,traffic:0,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/hallwest.htm',hits:4,traffic:0,name:'hallwest',ext:'htm',relurl:'dds.arc/miniwebventure/hallwest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/kitchen.htm',hits:4,traffic:0,name:'kitchen',ext:'htm',relurl:'dds.arc/miniwebventure/kitchen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/html-edit.htm',hits:4,traffic:0,name:'html-edit',ext:'htm',relurl:'jsPrj/html-edit.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/toilet.htm',hits:4,traffic:0,name:'toilet',ext:'htm',relurl:'dds.arc/miniwebventure/toilet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/shower.htm',hits:4,traffic:0,name:'shower',ext:'htm',relurl:'dds.arc/miniwebventure/shower.htm'}
,{url:'http://www.xs4all.nl/~zanstra/arc_index.htm',hits:3,traffic:5,name:'arc_index',ext:'htm',relurl:'arc_index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/index.htm',hits:3,traffic:17,name:'index',ext:'htm',relurl:'dds.arc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-Apr2004.html',hits:3,traffic:130,name:'stats-Apr2004',ext:'htm',relurl:'stats-Apr2004.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/inventory.htm',hits:3,traffic:1,name:'inventory',ext:'htm',relurl:'dds.arc/miniwebventure/icons/inventory.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nz1.html',hits:3,traffic:0,name:'nz1',ext:'htm',relurl:'dds.arc/Australia/nz1.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/go_up.htm',hits:3,traffic:0,name:'go_up',ext:'htm',relurl:'dds.arc/miniwebventure/go_up.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/vierhoek.html',hits:3,traffic:0,name:'vierhoek',ext:'htm',relurl:'dds.arc/vierhoek.html'}
,{url:'http://www.xs4all.nl/~zanstra/_template.htm',hits:3,traffic:0,name:'_template',ext:'htm',relurl:'_template.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:3,traffic:9,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/nothing.htm',hits:3,traffic:0,name:'nothing',ext:'htm',relurl:'dds.arc/miniwebventure/nothing.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery2.html',hits:3,traffic:0,name:'photoGallery2',ext:'htm',relurl:'dds.arc/Australia/photoGallery2.html'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm#kennify/index.htm',hits:3,traffic:63,name:'index',ext:'htm',relurl:'logs/jsLog.htm#kennify/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/muziek/piano.htm',hits:3,traffic:9,name:'piano',ext:'htm',relurl:'dds.arc/muziek/piano.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:3,traffic:3,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_north.htm',hits:3,traffic:0,name:'all_north',ext:'htm',relurl:'dds.arc/miniwebventure/all_north.htm'}
];
