/*stats, powered by toSource; (c) Cats Deep 2003*/
var lastUpdate_2004_5=new Date(2004,7-1,5,17,44,17,874);
var stats_2004_5=[{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm',hits:253,traffic:4291,name:'jsLog',ext:'htm',relurl:'logs/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/ServerXMLHTTP.htm',hits:225,traffic:1701,name:'ServerXMLHTTP',ext:'htm',relurl:'inTec/ServerXMLHTTP.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index.htm',hits:113,traffic:771,name:'index',ext:'htm',relurl:'index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea.htm',hits:104,traffic:1040,name:'safariIdea',ext:'htm',relurl:'inTec/safariIdea.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textareaOverflowVisible.htm',hits:82,traffic:65,name:'textareaOverflowVisible',ext:'htm',relurl:'inTec/safariIdea/textareaOverflowVisible.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/iframeDisplayNone.htm',hits:68,traffic:43,name:'iframeDisplayNone',ext:'htm',relurl:'inTec/safariIdea/iframeDisplayNone.htm'}
,{url:'http://www.xs4all.nl/~zanstra/fotos/index.htm',hits:60,traffic:385,name:'index',ext:'htm',relurl:'fotos/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/telNr.htm',hits:50,traffic:441,name:'telNr',ext:'htm',relurl:'dzLib/telNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/windowOpenWidth.htm',hits:34,traffic:69,name:'windowOpenWidth',ext:'htm',relurl:'inTec/safariIdea/windowOpenWidth.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/oneLiners.htm',hits:30,traffic:395,name:'oneLiners',ext:'htm',relurl:'logs/oneLiners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsmLib.htm',hits:29,traffic:120,name:'jsmLib',ext:'htm',relurl:'logs/jsmLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/setTimeout.htm',hits:26,traffic:41,name:'setTimeout',ext:'htm',relurl:'inTec/safariIdea/setTimeout.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/event-to.htm',hits:23,traffic:257,name:'event-to',ext:'htm',relurl:'dzLib/event/event-to.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/index.htm',hits:22,traffic:36,name:'index',ext:'htm',relurl:'inTec/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/captainsLog.htm',hits:20,traffic:340,name:'captainsLog',ext:'htm',relurl:'captainsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/documentLoad.htm',hits:19,traffic:47,name:'documentLoad',ext:'htm',relurl:'inTec/safariIdea/documentLoad.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats-cum.htm',hits:18,traffic:74,name:'stats-cum',ext:'htm',relurl:'stats-cum.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/script.htm',hits:17,traffic:29,name:'script',ext:'htm',relurl:'inTec/safariIdea/script.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/cookie.htm',hits:15,traffic:28,name:'cookie',ext:'htm',relurl:'dzLib/cookie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/ideaLog.htm',hits:15,traffic:71,name:'ideaLog',ext:'htm',relurl:'logs/ideaLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/index_opgeruimd.htm',hits:14,traffic:129,name:'index_opgeruimd',ext:'htm',relurl:'index_opgeruimd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/telefoonNummer.htm',hits:14,traffic:75,name:'telefoonNummer',ext:'htm',relurl:'inTec/telefoonNummer.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/index.htm',hits:13,traffic:13,name:'index',ext:'htm',relurl:'nrc/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ipe.htm',hits:12,traffic:51,name:'ipe',ext:'htm',relurl:'dzLib/ipe.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/toonladderTijd.htm',hits:12,traffic:58,name:'toonladderTijd',ext:'htm',relurl:'music/toonladderTijd.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis.htm',hits:12,traffic:77,name:'hysteresis',ext:'htm',relurl:'jsPrj/hysteresis.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/index.htm',hits:12,traffic:16,name:'index',ext:'htm',relurl:'logs/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/mkbPoezie.htm',hits:11,traffic:32,name:'mkbPoezie',ext:'htm',relurl:'mkbPoezie.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ubbParser.htm',hits:10,traffic:71,name:'ubbParser',ext:'htm',relurl:'dzLib/ubbParser.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/http.htm',hits:9,traffic:14,name:'http',ext:'htm',relurl:'inTec/http.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/phoneNumber.htm',hits:9,traffic:58,name:'phoneNumber',ext:'htm',relurl:'inTec/phoneNumber.htm'}
,{url:'http://www.xs4all.nl/~zanstra/stats.htm',hits:8,traffic:45,name:'stats',ext:'htm',relurl:'stats.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/index.htm',hits:8,traffic:3,name:'index',ext:'htm',relurl:'inTec/safariIdea/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/oneliners.htm',hits:7,traffic:12,name:'oneliners',ext:'htm',relurl:'jsPrj/oneliners.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/hysteresis1.htm',hits:7,traffic:43,name:'hysteresis1',ext:'htm',relurl:'jsPrj/hysteresis1.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/_addEvent.htm',hits:6,traffic:19,name:'_addEvent',ext:'htm',relurl:'dzLib/event/_addEvent.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/navigate.htm',hits:6,traffic:23,name:'navigate',ext:'htm',relurl:'nrc/navigate.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/get.htm',hits:6,traffic:18,name:'get',ext:'htm',relurl:'dzLib/get.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_text-flow.htm',hits:6,traffic:26,name:'_text-flow',ext:'htm',relurl:'inTec/_text-flow.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/urlNormalization.htm',hits:6,traffic:4,name:'urlNormalization',ext:'htm',relurl:'inTec/safariIdea/urlNormalization.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/index.htm',hits:6,traffic:15,name:'index',ext:'htm',relurl:'dzLib/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/music/uitleg.htm',hits:5,traffic:8,name:'uitleg',ext:'htm',relurl:'music/uitleg.htm'}
,{url:'http://www.xs4all.nl/~zanstra/contact.htm',hits:5,traffic:21,name:'contact',ext:'htm',relurl:'contact.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/data.htm',hits:5,traffic:7,name:'data',ext:'htm',relurl:'nrc/data.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/event/test.htm',hits:5,traffic:32,name:'test',ext:'htm',relurl:'dzLib/event/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/toSource.htm',hits:5,traffic:22,name:'toSource',ext:'htm',relurl:'dzLib/toSource.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/validateTelNr.htm',hits:5,traffic:5,name:'validateTelNr',ext:'htm',relurl:'jsPrj/validateTelNr.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/legal.htm',hits:5,traffic:13,name:'legal',ext:'htm',relurl:'dzLib/legal.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/windowOpen.htm',hits:5,traffic:49,name:'windowOpen',ext:'htm',relurl:'dzLib/windowOpen.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/index.htm',hits:5,traffic:2,name:'index',ext:'htm',relurl:'inTec/httpTutor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/feest/index.htm',hits:5,traffic:2,name:'index',ext:'htm',relurl:'feest/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/bijtjes.htm',hits:4,traffic:203,name:'bijtjes',ext:'htm',relurl:'nrc/bijtjes.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/eventLib.htm',hits:4,traffic:14,name:'eventLib',ext:'htm',relurl:'dzLib/eventLib.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/diamondBug.htm',hits:4,traffic:16,name:'diamondBug',ext:'htm',relurl:'inTec/diamondBug.htm'}
,{url:'http://www.xs4all.nl/~zanstra/nrc/nrc20011213.htm',hits:4,traffic:33,name:'nrc20011213',ext:'htm',relurl:'nrc/nrc20011213.htm'}
,{url:'http://www.xs4all.nl/~zanstra/potw/index.htm',hits:4,traffic:30,name:'index',ext:'htm',relurl:'potw/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/ddsindex.htm',hits:4,traffic:4,name:'ddsindex',ext:'htm',relurl:'ddsindex.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/ieMacProblems.htm',hits:4,traffic:12,name:'ieMacProblems',ext:'htm',relurl:'dzLib/ieMacProblems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/cos/cosinus-regel.htm',hits:4,traffic:13,name:'cosinus-regel',ext:'htm',relurl:'dds.arc/cos/cosinus-regel.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/textarea_lang.htm',hits:3,traffic:2,name:'textarea_lang',ext:'htm',relurl:'inTec/safariIdea/textarea_lang.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/listReplace.htm',hits:3,traffic:9,name:'listReplace',ext:'htm',relurl:'dzLib/listReplace.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/index.htm',hits:3,traffic:2,name:'index',ext:'htm',relurl:'motor/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/jsLog.htm',hits:3,traffic:4,name:'jsLog',ext:'htm',relurl:'dzLib/jsLog.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/htmlMail.htm',hits:3,traffic:21,name:'htmlMail',ext:'htm',relurl:'inTec/htmlMail.htm'}
,{url:'http://www.xs4all.nl/~zanstra/cert.htm',hits:3,traffic:5,name:'cert',ext:'htm',relurl:'cert.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/muziek/piano.htm',hits:3,traffic:27,name:'piano',ext:'htm',relurl:'dds.arc/muziek/piano.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/colorSyntaxJS.htm',hits:2,traffic:11,name:'colorSyntaxJS',ext:'htm',relurl:'dzLib/colorSyntaxJS.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery.html',hits:2,traffic:12,name:'photoGallery',ext:'htm',relurl:'dds.arc/Australia/photoGallery.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/jsListSearchSpeedTest.htm',hits:2,traffic:8,name:'jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/trackBack.htm',hits:2,traffic:4,name:'trackBack',ext:'htm',relurl:'inTec/trackBack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/zanstra/index.htm',hits:2,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/zanstra/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/engine.htm',hits:2,traffic:33,name:'engine',ext:'htm',relurl:'inTec/httpTutor/engine.htm'}
,{url:'http://www.xs4all.nl/~zanstra/motor/verbruik.htm',hits:2,traffic:4,name:'verbruik',ext:'htm',relurl:'motor/verbruik.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dzLib/callerStack.htm',hits:2,traffic:8,name:'callerStack',ext:'htm',relurl:'dzLib/callerStack.htm'}
,{url:'http://www.xs4all.nl/~zanstra/logs/jsLog.htm#kennify/index.htm',hits:2,traffic:36,name:'index',ext:'htm',relurl:'logs/jsLog.htm#kennify/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/vierhoek.html',hits:2,traffic:8,name:'vierhoek',ext:'htm',relurl:'dds.arc/vierhoek.html'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/httpTutor/helpItems.htm',hits:2,traffic:2,name:'helpItems',ext:'htm',relurl:'inTec/httpTutor/helpItems.htm'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/safariIdea/selectedStylesheetSet.htm',hits:2,traffic:2,name:'selectedStylesheetSet',ext:'htm',relurl:'inTec/safariIdea/selectedStylesheetSet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/csc/progress-bar.htm',hits:2,traffic:9,name:'progress-bar',ext:'htm',relurl:'csc/progress-bar.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/tabe/index.htm',hits:2,traffic:0,name:'index',ext:'htm',relurl:'dds.arc/tabe/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/index.htm',hits:2,traffic:2,name:'index',ext:'htm',relurl:'jsPrj/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/GoT/snowstorm/index.htm',hits:2,traffic:2,name:'index',ext:'htm',relurl:'GoT/snowstorm/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/icons/note.htm',hits:1,traffic:0,name:'note',ext:'htm',relurl:'dds.arc/miniwebventure/icons/note.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/toilet.htm',hits:1,traffic:1,name:'toilet',ext:'htm',relurl:'dds.arc/miniwebventure/toilet.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/javaScriptMan/index.htm',hits:1,traffic:1,name:'index',ext:'htm',relurl:'dds.arc/javaScriptMan/index.htm'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/test.htm',hits:1,traffic:0,name:'test',ext:'htm',relurl:'jsPrj/test.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/contact.html',hits:1,traffic:3,name:'contact',ext:'htm',relurl:'dds.arc/contact.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/capeyork.html',hits:1,traffic:4,name:'capeyork',ext:'htm',relurl:'dds.arc/Australia/capeyork.html'}
,{url:'http://www.xs4all.nl/~zanstra/jsPrj/_jsListSearchSpeedTest.htm',hits:1,traffic:2,name:'_jsListSearchSpeedTest',ext:'htm',relurl:'jsPrj/_jsListSearchSpeedTest.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/all_north.htm',hits:1,traffic:0,name:'all_north',ext:'htm',relurl:'dds.arc/miniwebventure/all_north.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/photoGallery2.html',hits:1,traffic:6,name:'photoGallery2',ext:'htm',relurl:'dds.arc/Australia/photoGallery2.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/nt.html',hits:1,traffic:3,name:'nt',ext:'htm',relurl:'dds.arc/Australia/nt.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/route.html',hits:1,traffic:0,name:'route',ext:'htm',relurl:'dds.arc/route.html'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/miniwebventure/go_up.htm',hits:1,traffic:1,name:'go_up',ext:'htm',relurl:'dds.arc/miniwebventure/go_up.htm'}
,{url:'http://www.xs4all.nl/~zanstra/dds.arc/Australia/cch.html',hits:1,traffic:3,name:'cch',ext:'htm',relurl:'dds.arc/Australia/cch.html'}
,{url:'http://www.xs4all.nl/~zanstra/inTec/_htmlMail.htm',hits:1,traffic:7,name:'_htmlMail',ext:'htm',relurl:'inTec/_htmlMail.htm'}
];
